### ISSUE TITLE
Hitting secondary rate limit

### ISSUE THREAD

**Issue by timofurrer** [dessant/repo-lockdown#10]
I'm using this Action to automatically close all open PRs in a repository, however, pretty much at least once a day it fails because it's hitting GitHubs secondary rate limit. 

Is there a way to avoid this? There is almost no traffic in that repository, so it shouldn't make lots of requests, right?

- The repository is:
https://github.com/gitlabhq/terraform-provider-gitlab
- The config I'm using is:

```yaml
name: 'Lockdown'

on:
  pull_request_target:
    types: opened
  schedule:
    - cron: '0 * * * *'

permissions:
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v2
        with: 
          process-only: prs
          skip-closed-pr-comment: true
          pr-comment: ...
```

- a failed action: https://github.com/gitlabhq/terraform-provider-gitlab/actions/runs/10085929776
