### ISSUE TITLE
Comment only on open pull requests and issues, not closed ones

### ISSUE THREAD

**Issue by mitar** [dessant/repo-lockdown#4]
Amazing app! I have only one comment. I know there is `skipCreatedBefore` to set what to process, but I would prefer that all issues and pull requests are closed/locked, but only on those which were initially open a comment is left. Would that be possible?

**Comment by dessant** [comment]
> but I would prefer that all issues and pull requests are closed/locked, but only on open ones a comment is left

I'm not sure I understand. Do you mean to lock issues and pull requests that have already been closed before the app was installed, but on issues that have been open, only leave a comment, without closing and locking?

**Comment by dessant** [comment]
Or by `only on open ones` did you mean `only on new ones`?

**Comment by dessant** [comment]
Ok, now I've also read the issue title :yum: , and I think I understand what you want.

**Comment by dessant** [comment]
Actually I still have a hard time figuring out what's the exact behavior you need, please describe the feature in detail.

**Comment by mitar** [comment]
Sorry for confusion. I edited the description. To maybe repeat here, too. So some issues and PRs in my repo are open, and some of them are closed. Then I add this app, and currently it will go over all of them and close (if not already) and lock them and leave a comment. What I would like is that:
* For closed issues and PRs, it just locks them.
* For open issues and PRs, it closes/locks them, and leaves a comment.

**Comment by dessant** [comment]
Ok, now it's clear, thanks for following up! I see why you need the feature, but it is a bit arbitrary, and it would need several config options to configure which issues can be selectively locked or commented on depending on their state.

It may be better to use [Lock Threads](https://github.com/dessant/lock-threads) to lock your backlog of closed issues without leaving a comment, then remove the workflow file to disable the action.

For open issues and PRs you can then use Repo Lockdown and disable locking in the config.

**Comment by dessant** [comment]
Add this config file unchanged to `.github/workflows/lock.yml`, it will process 50 issues and PRs every hour. Make sure to remove the file when your backlog has been handled.

```yaml
name: 'Lock threads'

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  lock:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v2
        with:
          github-token: ${{ github.token }}
          issue-lock-inactive-days: '0'
          issue-lock-reason: ''
          pr-lock-inactive-days: '0'
          pr-lock-reason: ''
```
